import localFont from "next/font/local";
import "./globals.css";
import '@/app/components/Menu/Menu'
import Menu from "@/app/components/Menu/Menu";
import { Noto_Sans } from 'next/font/google';

const notoSans = Noto_Sans({subsets : ['latin']});


export const metadata = {
  title: "ameny.online",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${notoSans}  antialiased`}
      >
        <Menu />
        {children}
      </body>
    </html>
  );
}
